backend/autocli/urls.py
# Django Import:
from django.utils.translation import gettext_lazy as _
from django.conf.urls.i18n import i18n_patterns
from django.urls import path, include
from django.contrib import admin

# Admin URL pattern:
urlpatterns = [
    path('admin/', admin.site.urls),
]

# Application URLs patterns:
urlpatterns += i18n_patterns (
    path('inventory/device/', include('inventory.urls.device_url')),
    path('inventory/color/', include('inventory.urls.color_url')),
    path('inventory/credential/', include('inventory.urls.credential_url')),
    path('inventory/folder/', include('inventory.urls.folder_url')),
    prefix_default_language=True,
)

backend/inventory/models/folde_model.py
# Django Import:
from django.utils.translation import gettext_lazy as _
from django.db import models

# Base Model Import:
from autocli.basemodel.basemodel import BaseMainModel

# Other models Import:
from .credential_model import Credential
from .device_model import Device

# Constants Import:
from ..constants import ICONS


# Folder model:
class Folder(BaseMainModel):
    """ Folders allow you to group network devices. """

    class Meta:
        
        # Model name values:
        verbose_name = _('Folder')
        verbose_name_plural = _('Folders')

    # All defaults main values:
    ico = models.IntegerField(
        verbose_name=_('Default device Icon'),
        help_text=_('Folder default network device graphic representation.'),
        choices=ICONS,
        default=0
    )
    ssh_port = models.IntegerField(
        verbose_name=_('Default SSH port'),
        help_text=_('Folder default SSH protocol port number.'),
        default=22
    )
    https_port = models.IntegerField(
        verbose_name=_('Default HTTPS port'),
        help_text=_('Folder default HTTPS protocol port number.'),
        default=443
    )

    # All defaults security and credentials:
    credential = models.ForeignKey(
        Credential,
        verbose_name=_('Default credential'),
        help_text=_('Folder default credential needed to establish SSH / HTTPS connection.'),
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )
    secret = models.CharField(
        verbose_name=_('Default secret'),
        help_text=_('Folder default network device secret password.'),
        max_length=64,
        null=True,
        blank=True
    )
    certificate = models.BooleanField(
        verbose_name=_('Default certificate'),
        help_text=_('Folder default certificate check status.'),
        default=False
    )

    # Relationships with other models:
    root_folder = models.ForeignKey(
        'self',
        verbose_name=_('Root folder'),
        help_text=_('The parent folder to witch the current folder belongs.'),
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )
    devices = models.ManyToManyField(
        Device,
        verbose_name=_('Devices'),
        help_text=_('All devices that belongs to current folder.'),
        blank=True
    )

backend/autocli/baseview-old/views/create_view.py
# Base view Import:
from ..baseview import BaseView


# Create View class:
class CreateView:

    pass

backend/autocli/baseview-old/views/delete_view.py
# Base view Import:
from ..baseview import BaseView


# Delete View class:
class DeleteView:

    pass

backend/autocli/baseview-old/views/detail_view.py
# Base view Import:
from ..baseview import BaseView


# Detai lView class:
class DetailView:

    pass

backend/autocli/baseview-old/views/list_view.py
# Django Imports:
from django.utils.translation import gettext_lazy as _
from django.shortcuts import render, get_object_or_404

# Base view Import:
from ..baseview import BaseView


# List View class:
class ListView(BaseView):

    # GET request response page:
    def get(self, request, *args, **kwargs):
        super().get(request, *args, **kwargs)

        # Generate default page name if not provided:
        self.page_data['page_name'] = self._get_page_name(_('Display all'), True)

        # Return all collected objects:
        self.page_data['objects'] = self._collect_objects(request)

        # Collect all filtered value used to create template filter options:
        self._get_filter_template()


        self.page_data['output'] = self.collect_model_attributes_names()

        return render(request, self._get_attribute(self.template, 'base_views/list_view.html'), self.page_data)

backend/autocli/baseview/views/create_view.py
# Django language import:
from django.utils.translation import gettext_lazy as _

# Base view Import:
from ..subclasses.base_view import BaseView

# Django Import:
from django.urls import reverse_lazy

# Django view Import:
from django.views.generic.edit import CreateView as DjangoView


# Create View class:
class CreateView(BaseView, DjangoView):

    # Pre-populated attributes:
    template_name = 'base_views/create_update_view.html'
    plural = True
    success_url = '/'
    page_name_action = _('Create a new')

    field_set = None

    def post(self, request, *args, **kwargs):
        """ Overwrite post function. """

        # Inherit functionality from get function:
        super().get(request, *args, **kwargs)
        # Collect context data:
        context = self.get_context_data()

        ### Create return URL ###
        # Collect current URL:
        url = self.request.build_absolute_uri()
        # Option one save and create new one:
        if request.POST.get('save_one') is not None:
            requested_site = self._collect_class_name() + ':create'
            self.success_url = reverse_lazy(requested_site)
        # Option one save and edit:
        elif request.POST.get('save_two') is not None:
            self.success_url = url
        # Option one save and return to list view:self._collect_class_name() + ':list'
        elif request.POST.get('save_three') is not None:
            requested_site = self._collect_class_name() + ':list'
            self.success_url = reverse_lazy(requested_site)

        # Return HTML response:
        return super().post(request, *args, **kwargs)

backend/autocli/baseview/views/delete_view.py
# Django language import:
from django.utils.translation import gettext_lazy as _

# Base view Import:
from ..subclasses.base_view import BaseView

# Django Import:
from django.urls import reverse_lazy


# Django view Import:
from django.views.generic.edit import DeleteView as DjangoView


# Delete View class:
class DeleteView(BaseView, DjangoView):

    # Pre-populated attributes:
    template_name = 'base_views/delete_view.html'
    singular = True
    success_url = '/'
    page_name_action = _('Delete')

    def get(self, request, *args, **kwargs):
        """ Overwrite get function. """

        # Inherit functionality from get function:
        super().get(request, *args, **kwargs)
        # Collect context data:
        context = self.get_context_data()
        # Submit object PK to HTML template:
        context['object_pk'] = self.object.pk
    
        # Return HTML response:
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        """ Overwrite post function. """

        # Inherit functionality from get function:
        super().get(request, *args, **kwargs)
        # Collect context data:
        context = self.get_context_data()
        # Submit object PK to HTML template:
        context['object_pk'] = self.object.pk
        # Create return URL:
        requested_site = self._collect_class_name() + ':list'
        self.success_url = reverse_lazy(requested_site)

        # Return HTML response:
        return super().post(request, *args, **kwargs)

backend/autocli/baseview/views/detail_view.py
# Django language import:
from django.utils.translation import gettext_lazy as _

# Base view Import:
from ..subclasses.base_view import BaseView

# Django view Import:
from django.views.generic import DetailView as DjangoView

# Detail lView class:
class DetailView(BaseView, DjangoView):

    # Pre-populated attributes:
    template_name = 'base_views/detail_view.html'
    singular = True

    def get(self, request, *args, **kwargs):
        """ Overwrite get function. """

        # Inherit functionality from get function:
        super().get(request, *args, **kwargs)
        # Collect context data:
        context = self.get_context_data()
        # Submit object PK to HTML template:
        context['object_pk'] = self.object.pk
    
        # Return HTML response:
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        """ Overwrite post function. """

        # Inherit functionality from get function:
        super().get(request, *args, **kwargs)
        # Collect context data:
        context = self.get_context_data()
        # Submit object PK to HTML template:
        context['object_pk'] = self.object.pk

        # Return HTML response:
        return super().post(request, *args, **kwargs)

backend/autocli/baseview/views/list_view.py
# Django language import:
from django.utils.translation import gettext_lazy as _

# Python Import:
import re

# Base view Import:
from ..subclasses.base_view import BaseView

# Django view Import:
from django.views.generic import ListView as DjangoView


# List View class:
class ListView(BaseView, DjangoView):

    # Blank value attributes:
    filterset = None
    list_view = None

    # Pre-populated attributes:
    template_name = 'base_views/list_view.html'
    page_name_action = _('List all')
    plural = True
    paginate_by = 9

    def get_queryset(self):
        """ Overwrite get_queryset function. """

        # Inherit functionality from get_queryset function:
        queryset = super().get_queryset()
        # Filter results based on provided filter class:
        self.filter_results = self.filterset(self.request.GET, queryset=queryset)
        # Set value of no_search_result variable:
        self.no_search_result = True if not self.filter_results.qs else False

        # Return serache results:
        return self.filter_results.qs.distinct()

    def get_context_data(self, **kwargs):
        """ Overwrite get_context_data function. """

        # Inherit functionality from get_context_data function:
        context = super().get_context_data(**kwargs)
        # Submit query string to HTML template:
        context['query_string'] = self.get_query_string()
        # Submit no_search_result variable to HTML template:
        context['no_search_result'] = self.no_search_result
        # Submit filter class to HTML template:
        context['filter'] = self.filter_results
        # Submit list_view value to HTML template:
        context['list_view'] = self.list_view
        # Submit list view js to HTML template:
        context['view_js'] = 'js/list_view.js'
        # Submit edit to HTML template:
        context['edit'] = 1

        # Return context data:
        return context

    def get_query_string(self):
        """ Returns url query string base on get request url. """

        # Collect URL query string from http request:
        query_string = self.request.META.get('QUERY_STRING', '')
        # Validate collected query string to remove page value:
        validated_query_string = '&'.join([x for x in re.findall(
            r'(\w*=\w{1,})', query_string) if not 'page=' in x])

        # Return validated query string with & symbol or blank string:
        return '&' + validated_query_string if (validated_query_string and not self.no_search_result) else ''

backend/autocli/baseview/views/update_view.py
# Django language import:
from django.utils.translation import gettext_lazy as _

# Base view Import:
from ..subclasses.base_view import BaseView

# Django Import:
from django.urls import reverse_lazy

# Django view Import:
from django.views.generic.edit import UpdateView as DjangoView


# Update View class:
class UpdateView(BaseView, DjangoView):

    # Pre-populated attributes:
    template_name = 'base_views/create_update_view.html'
    singular = True
    page_name_action = _('Update')
    success_url = '/'

    def get(self, request, *args, **kwargs):
        """ Overwrite get function. """

        # Inherit functionality from get function:
        super().get(request, *args, **kwargs)
        # Collect context data:
        context = self.get_context_data()
        # Submit object PK to HTML template:
        context['object_pk'] = self.object.pk
    
        # Return HTML response:
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        """ Overwrite post function. """

        # Inherit functionality from get function:
        super().get(request, *args, **kwargs)
        # Collect context data:
        context = self.get_context_data()
        # Submit object PK to HTML template:
        context['object_pk'] = self.object.pk

        ### Create return URL ###
        # Collect current URL:
        url = self.request.build_absolute_uri()
        # Option one save and create new one:
        if request.POST.get('save_one') is not None:
            requested_site = self._collect_class_name() + ':create'
            self.success_url = reverse_lazy(requested_site)
        # Option one save and edit:
        elif request.POST.get('save_two') is not None:
            self.success_url = url
        # Option one save and return to list view:
        elif request.POST.get('save_three') is not None:
            requested_site = self._collect_class_name() + ':list'
            self.success_url = reverse_lazy(requested_site)

        # Return HTML response:
        return super().post(request, *args, **kwargs)

backend/templates/base_views/create_update_view.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

    {% block panel %}
        {% include "base_views/components/panel.html" %}
    {% endblock panel %}

    <!-- Add form -->
    <div class="grid-box grid-padding create-view">
        <form method="post">
            <div class="create-view-form">
                {% csrf_token %}
                {% for field in form %}
                    <div class="create-view-form-item">
                        {% if 'id_hexadecimal' in field.label_tag %}
                            {{ field.label_tag }}
                            <input type="color" name="hexadecimal" maxlength="7" required="" id="id_hexadecimal">
                            <div class="create-view-form-error">
                                {{ field.errors }}
                            </div>
                        {% else %}
                            {{ field.label_tag }}
                            {{ field }}
                            <div class="create-view-form-error">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                        {% if field.help_text %}
                            {{ field.help_text|safe }}
                        {% endif %}
                    </div>
                {% endfor %}
            </div>
            <div class="create-view-buttons">
                <input class="button blue-button click-animation" type="submit" name="save_one" value='{% translate "Save and create new one" %}'>
                <input class="button yellow-button click-animation" type="submit" name="save_two" value='{% translate "Save and stay" %}'>
                <input class="button green-button click-animation" type="submit" name="save_three" value='{% translate "Save" %}'>
            </div>
            <p>
                {{ form.subject.errors }}
                {{ form.subject.label_tag }}
                {{ form.subject }}
            </p>
        </form>
    </div>

{% endblock %}

backend/templates/base_views/create_view.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

    {% block panel %}
        {% include "base_views/components/panel.html" %}
    {% endblock panel %}

    <!-- Add form -->
    <div class="grid-box grid-padding create-view">
        <form method="post">
            <div class="create-view-form">
                {% csrf_token %}
                {% for field in form %}
                    <div class="create-view-form-item">
                        {{ field.label_tag }} {{ field }}
                        {{ field.errors }}
                    </div>
                {% endfor %}
            </div>
            <div class="create-view-buttons">
                <input class="button blue-button click-animation" type="submit" name="save_one" value='{% translate "Save and create new one" %}'>
                <input class="button yellow-button click-animation" type="submit" name="save_two" value='{% translate "Save and stay" %}'>
                <input class="button green-button click-animation" type="submit" name="save_three" value='{% translate "Save" %}'>
            </div>
            <p>
                {{ form.subject.errors }}
                {{ form.subject.label_tag }}
                {{ form.subject }}
            </p>
        </form>
    </div>

{% endblock %}

backend/templates/base_views/delete_view.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

    {% block panel %}
        {% include "base_views/components/panel.html" %}
    {% endblock panel %}

    <div class="grid-box grid-padding">
        <form method="post">
            {% csrf_token %}
            <p>{% translate "Are you sure you want to delete" %} <strong>{{ object }}</strong> {{ class_name|title }}?</p>
            {{ form }}
            <input class="button red-button click-animation top-margin" type="submit" name="save_three" value='{% translate "Delete" %}' autofocus="">
        </form>
    </div>

{% endblock %}

backend/templates/base_views/detail_view.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}

    {% block panel %}
        {% include "base_views/components/panel.html" %}
    {% endblock panel %}

    <p>{{ object.pk }} - {{ object.name }} - {{ object.hostname }}</p>

{% endblock %}

backend/templates/base_views/list_view.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load auto_tags %}

{% block content %}

    {% block panel %}
        {% include "base_views/components/panel.html" %}
    {% endblock panel %}

    <!-- Search panel -->
    {% if filter %}
        <form method="GET">
            {% for field in filter.form %}

                {% if field.html_name == 'name__contains' %}
                    <div class="grid-box" id="content-search">
                        {{ field }}
                        <button class="click-animation" type="submit">
                            <img src="{% static 'ico/main/search.svg' %}" alt="Search">
                        </button>
                        <div class="click-animation" id="content-filter-button" >
                            <img src="{% static 'ico/main/filter.svg' %}" alt="Filter">
                        </div>
                    </div>
                {% endif %}

            {% endfor %}
                
            <div id="content-filter" class="grid-box grid-padding gird-filter collapse">
                {% for field in filter.form %}
                    {% if field.html_name != 'name__contains' %}
                        {{ field.label_tag }} {{ field }}
                    {% endif %}
                {% endfor %}
            </div>
            
        </form>
    {% endif %}

    {% if no_search_result %}
        <div class="no-object-to-display">
            <div>
                <img src="{% static 'ico/main/hidden.svg' %}" alt="No output">
                </br></br>
                <p>{% translate "There is nothing to display :(" %}</p>
            </div>
        </div>
    {% else %}

        {% if display_version == 1 %}
            <!-- Grid container for models -->
            <div id="content-grid">
                
                {% for object in object_list %}
                    <!-- Single model item -->
                    <div class="model-item">
                        <div class="grid-padding">
                            <div class="model-item-status">
                                <!-- Box activity -->
                                <div class="ball-box">
                                    {% if object.active is True or object.active is False %}
                                        <!-- Active status -->
                                        {% if object.active is True %}
                                            <div class="ball ball-active" aria-label="Active"></div>
                                        {% else %}
                                            <div class="ball ball-inactive" aria-label="Active"></div>
                                        {% endif %}
                                    {% endif %}
                                    {% if object.ssh_status is True or object.ssh_status is False %}
                                        <!-- SSH status -->
                                        {% if object.ssh_status is True %}
                                            <div class="ball ball-active" aria-label="SSH status"></div>
                                        {% else %}
                                            <div class="ball ball-inactive" aria-label="SSH status"></div>
                                        {% endif %}
                                    {% endif %}
                                    {% if object.https_status is True or object.https_status is False %}
                                        <!-- HTTPS status -->
                                        {% if object.https_status is True %}
                                            <div class="ball ball-active" aria-label="HTTPS status"></div>
                                        {% else %}
                                            <div class="ball ball-inactive" aria-label="HTTPS status"></div>
                                        {% endif %}
                                    {% endif %}
                                </div>
                                <div class="box-buttons collapse">
                                    <a class="button green-button click-animation" href="{% url update_link pk=object.pk %}">{% translate "Update" %}</a>
                                    <a class="button red-button click-animation" href="{% url delete_link pk=object.pk %}">{% translate "Delete" %}</a>
                                </div>
                            </div>

                            <!-- Single model item header -->
                            <div class="model-item-header">
                                {% if object.ico >= 0 %}
                                    <img class="box-header-svg" src="/{{ object.get_ico_display }}" alt="switch">
                                {% elif object.ico == 'hexadecimal' %}
                                    <div class="ico_hexadecimal" style='background: {{ object.hexadecimal }};'></div>
                                {% endif %}
                                <div>
                                    <h3><a href="{% url detail_link pk=object.pk %}">{{ object.name|title }}</a></h3>
                                    <q>{% verbose_name object 'created' %}: {{ object.created }}</q></br>
                                    <q>{% verbose_name object 'updated' %}: {{ object.updated }}</q></br>
                                </div>
                            </div>

                            <!-- Single model item body -->
                            <div class="model-item-body">
                                {% if list_view %}
                                    <table>
                                        {% for row in list_view %}
                                            <tr>
                                                <th>{% verbose_name object row %}:</th>
                                                <td>{% object_attribute_value object row %}</td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        {% elif display_version == 2 %}
            <!-- Table -->
            <div class="table grid-box">

                <table class="shadow table-hover table-blue">
                    <thead>
                        <tr>
                            <th scope="col">{% translate "Name" %}</th>
                            {% if list_view %}
                                {% for row in list_view %}
                                    <th>{{ row|title }}</th>
                                {% endfor %}
                            {% endif %}
                            <th id="table-buttons-action" class="collapse">{% translate "Actions" %}</th>
                    </tr>
                    </thead>
                    <tbody>
                        {% for object in object_list %}
                            <tr>
                                <th><a href="{% url detail_link pk=object.pk %}">{{ object.name }}</a></th>
                                {% if list_view %}
                                    {% for row in list_view %}
                                        <td>{% object_attribute_value object row %}</td>
                                    {% endfor %}
                                {% endif %}
                                <th class="table-buttons-box collapse">
                                    <a class="button green-button click-animation" href="{% url update_link pk=object.pk %}">{% translate "Update" %}</a>
                                    <a class="button red-button click-animation" href="{% url delete_link pk=object.pk %}">{% translate "Delete" %}</a>
                                </th>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        {% endif %}
    {% endif %}

    <!-- Pagination panel -->
    {% if page_obj %}
        <div id="content-paginator">
            <div class="grid-box">
                
                {% if page_obj.has_previous %}
                    <div class="paginator-section">
                        <a href="?page=1{{ query_string }}" label="{% translate 'First page' %}" class="action-button click-animation">
                            <img src="{% static 'ico/main/left-arrow1.svg' %}" alt="Ico">
                        </a>
                        <a href="?page={{ page_obj.previous_page_number }}{{ query_string }}" label="{% translate 'Precious page' %}" class="action-button click-animation">
                            <img src="{% static 'ico/main/left-arrow2.svg' %}" alt="Ico">
                        </a>
                    </div>
                {% else %}
                    <div class="paginator-section">
                        <a label="{% translate 'This is first page' %}" class="action-button click-animation">
                            <img src="{% static 'ico/main/left-arrow3.svg' %}" alt="Ico">
                        </a>
                    </div>
                {% endif %}

                <span class="current">
                    <p>{% translate 'Page' %} {{ page_obj.number }} {% translate 'of' %} {{ page_obj.paginator.num_pages }}</p>
                </span>

                {% if page_obj.has_next %}
                    <div class="paginator-section">
                        <a href="?page={{ page_obj.next_page_number }}{{ query_string }}" label="{% translate 'Next page' %}" class="action-button click-animation">
                            <img src="{% static 'ico/main/right-arrow2.svg' %}" alt="Ico">
                        </a>
                        <a href="?page={{ page_obj.paginator.num_pages }}{{ query_string }}" label="{% translate 'Last page' %}" class="action-button click-animation">
                            <img src="{% static 'ico/main/right-arrow1.svg' %}" alt="Ico">
                        </a>
                    </div>
                {% else %}
                    <div class="paginator-section">
                        <a label="{% translate 'No more pages' %}" class="action-button click-animation">
                            <img src="{% static 'ico/main/right-arrow3.svg' %}" alt="Ico">
                        </a>
                    </div>
                {% endif %}

            </div>
        </div>
    {% endif %}

{% endblock %}